# Generated by Django 2.1.5 on 2021-08-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20210805_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='last_viewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
