# Generated by Django 2.1.5 on 2021-08-06 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rango', '0009_category_last_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='followed',
            field=models.ManyToManyField(blank=True, related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
